---
roles:
  # PostgreSQL
  - name: geerlingguy.postgresql
    version: 2.2.0
  # Apache
  - name: geerlingguy.apache
    version: 3.1.0
  # Redis
  - name: davidwittman.redis
    version: 1.2.7
  # uwsgi
  - name: cchurch.uwsgi
    version: 0.5.1
  # virtualenv
  - name: cchurch.virtualenv
    version: 0.6.4
  # SystemD
  - name: 0x0i.systemd
    version: v0.2.2
